remote_theme: pmarsceill/just-the-docs

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
    "Get the GitHub repo":
      - "//github.com/mariohernandez/component-based-development"

# Color scheme currently only supports "dark" or nil (default)
color_scheme: "nil"
